secret: somesecret
expiration_time: 100


spring:
  application:
    name: security-application
  profiles:
    active: dev
  jpa:
    flyway:
      enabled: true
      validate-on-migrate: true
      location: "classpath:db.migration"
    database: h2
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    properties:
  datasource:
    database-platform: org.hibernate.dialect.H2Dialect
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8080 